// Rich graph specs for each Reece procedure. Each procedure becomes a
// React Flow graph (phase headers + step nodes + branch nodes + output
// nodes), matching the Janus Core visual model. Step nodes carry a
// short label + a long description; clicking opens FlowDetailPanel,
// which surfaces tools, guardrails, examples, and outputs.
//
// To add or edit a procedure: extend REECE_PROCEDURE_SPECS below. The
// renderer (buildReeceFlowGraph) reads only what's here — no need to
// touch ProcedureMap.tsx for content changes.

export interface ReeceStepSpec {
  id: string;
  label: string;
  stepNumber: number;
  shortDesc: string;
  longDesc: string;
  tools?: string[];
  guardrails?: string[];
  examples?: string[];
  outputs?: string[];
  mandatory?: boolean;
  x: number;
  y: number;
}

export interface ReecePhaseSpec {
  id: string;
  label: string;
  color: string;
  x: number;
  y: number;
}

export interface ReeceEdgeSpec {
  from: string;
  to: string;
  label?: string;
  branch?: boolean;
  color?: string;
  sourceHandle?: 'right' | 'bottom';
  targetHandle?: 'left' | 'top';
}

export interface ReeceProcedureSpec {
  id: string;
  title: string;
  subtitle: string;
  file: string;
  level: string;
  objective: string;
  automation: string;
  accent: string;
  phases: ReecePhaseSpec[];
  steps: ReeceStepSpec[];
  edges: ReeceEdgeSpec[];
}

const COL = {
  intake: '#5fd4d4',
  discovery: '#7aa6e6',
  execute: '#5fd47a',
  validate: '#d4a55f',
  close: '#a77bdb',
};

// ─── 1. Ticket intake and routing ────────────────────────────────
const INTAKE: ReeceProcedureSpec = {
  id: 'reece-intake',
  title: 'Ticket Intake and Routing',
  subtitle: 'Convert every Jira ticket into a scoped plan before touching anything.',
  file: 'dump/reece_ai/procedures/ticket-intake-and-routing.md',
  level: 'L1 triage',
  objective: 'Classify the request, identify blast radius, find prior context, gather live evidence, and route to the matching procedure — without making assumptions.',
  automation: 'Safe for assisted triage and procedure suggestion. Read-only by default; only the routing decision is automated.',
  accent: COL.intake,
  phases: [
    { id: 'p-read',     label: 'READ',     color: COL.intake,    x: 80,   y: -60 },
    { id: 'p-classify', label: 'CLASSIFY', color: COL.discovery, x: 480,  y: -60 },
    { id: 'p-evidence', label: 'EVIDENCE', color: COL.execute,   x: 880,  y: -60 },
    { id: 'p-route',    label: 'ROUTE',    color: COL.close,     x: 1280, y: -60 },
  ],
  steps: [
    { id: 'sync', label: 'Sync the ticket', stepNumber: 1,
      shortDesc: 'Pull latest Jira state into the local catalog',
      longDesc: 'Run the Reece catalog sync (or wait for the next daily fire) so the local ticket folder reflects the latest description, comments, attachments, and links. Stale local notes lead to wrong assumptions.',
      tools: ['scripts/reece-catalog-sync.mjs', 'mcp__claude_ai_Atlassian'],
      outputs: ['Fresh dump/reece_ai/tickets/DE-XX/README.md with latest auto-section'],
      mandatory: true, x: 40, y: 20,
    },
    { id: 'read', label: 'Read fully', stepNumber: 2,
      shortDesc: 'Description + comments + linked issues + attachments',
      longDesc: 'Read every comment in order. Read attached specs / Excel mappings. Open linked Confluence pages. Check the parent epic for the broader business goal that this ticket implements.',
      examples: ['DE-87 → parent DE-48 is the PriceFX rollout. Sibling DE-89 is the competitor-data slice.'],
      outputs: ['Mental model of what the requester actually wants'],
      mandatory: true, x: 40, y: 180,
    },
    { id: 'classify', label: 'Classify request type', stepNumber: 3,
      shortDesc: 'Map to one of 8 known request shapes',
      longDesc: 'Which procedure does this ticket map to? Categories: data-quality investigation, new/changed Snowflake object, Snowflake permission/access, new ingestion job, existing ingestion fix, migration/lineage dictionary, Confluence/docs only, or ambiguous-needs-clarification.',
      examples: ['"Why are there 0 rows in X" → data-quality', '"Grant Y access to Z" → permissions', '"New daily feed from API W" → ingestion job creation'],
      outputs: ['One of 8 classifications + a procedure file path'],
      mandatory: true, x: 440, y: 20,
    },
    { id: 'blast', label: 'Identify blast radius', stepNumber: 4,
      shortDesc: 'What systems + envs + consumers does this touch',
      longDesc: 'Map every system in scope (Snowflake, Talend, TMC, source API, SFTP, GitHub, Jira, Confluence), every environment (dev/UAT/prod), and every downstream consumer (analyst, dashboard, Pricefx, Qlik). A small wording change in Jira can hide a production-mutation request.',
      outputs: ['Risk classification: read-only / bounded mutation / human-only'],
      mandatory: true, x: 440, y: 180,
    },
    { id: 'history', label: 'Search local history', stepNumber: 5,
      shortDesc: 'LEARNINGS + jobs + tickets + memory corrections',
      longDesc: 'Before touching live systems, check what the catalog already knows. Grep LEARNINGS.md for the affected object/source/job. Search tickets/ for prior tickets about the same system. Check durable memory (mcp__memory__recall) for prior corrections about this exact area.',
      tools: ['Grep over dump/reece_ai/', 'mcp__memory__recall'],
      outputs: ['List of prior relevant tickets/jobs/learnings'],
      mandatory: true, x: 840, y: 20,
    },
    { id: 'live', label: 'Live evidence', stepNumber: 6,
      shortDesc: 'Snowflake + TMC + GitHub before planning',
      longDesc: 'Hit the live systems read-only: Snowflake object existence/grants/freshness, TMC job runtime state and schedule, GitHub for the actual .item path and branch convention, Confluence for any standard already defined. Static catalog notes are corroborating evidence, not authority.',
      tools: ['scripts/snowflake-query.mjs', 'mcp__github__*', 'mcp__claude_ai_Atlassian__*'],
      guardrails: ['Read-only only', 'Stop after 1-2 Snowflake auth failures (sandbox lockout)'],
      outputs: ['Notes on actual current state of each touched object'],
      mandatory: true, x: 840, y: 180,
    },
    { id: 'plan', label: 'Write execution plan', stepNumber: 7,
      shortDesc: 'Scope, evidence, change, validation, rollback',
      longDesc: 'The plan must include: scope, evidence gathered, proposed change, validation (how you will know it worked), rollback or mitigation, open questions, and whether the ticket is safe for read-only/bounded-mutation/human-only execution.',
      examples: ['Use the Ticket Triage Template in the .md procedure'],
      outputs: ['A ticket-triage block ready to paste into Jira or your notes'],
      mandatory: true, x: 1240, y: 20,
    },
    { id: 'route', label: 'Route to matching procedure', stepNumber: 8,
      shortDesc: 'Hand off to the right runbook',
      longDesc: 'Open the procedure that matches the classification. Each procedure has its own discovery + execute + validate flow with its own guardrails. Don\'t freelance; the procedure exists because patterns matter.',
      examples: ['data-quality → snowflake-investigation-and-data-quality.md', 'permissions → snowflake-objects-and-permissions.md', 'job work → ingestion-job-creation.md'],
      outputs: ['Active procedure for the rest of the ticket'],
      mandatory: true, x: 1240, y: 180,
    },
    { id: 'close', label: 'Close the loop', stepNumber: 9,
      shortDesc: 'Jira update + local notes + durable lessons',
      longDesc: 'After execution finishes (in whichever sub-procedure ran), come back here to write: an evidence-based Jira comment with findings + validation, manual notes in the ticket\'s local README, and a durable learning in LEARNINGS.md only if this helps future tickets.',
      tools: ['mcp__claude_ai_Atlassian__add_jira_comment', 'Edit on dump/reece_ai/tickets/DE-XX/README.md', 'Edit on dump/reece_ai/LEARNINGS.md'],
      outputs: ['Jira comment, updated ticket folder, possibly a new learning'],
      mandatory: true, x: 1240, y: 360,
    },
  ],
  edges: [
    { from: 'sync', to: 'read' },
    { from: 'read', to: 'classify', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'classify', to: 'blast' },
    { from: 'blast', to: 'history', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'history', to: 'live' },
    { from: 'live', to: 'plan', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'plan', to: 'route' },
    { from: 'route', to: 'close' },
  ],
};

// ─── 2. Snowflake investigation and data quality ─────────────────
const DATA_QA: ReeceProcedureSpec = {
  id: 'reece-data-quality',
  title: 'Snowflake Investigation and Data Quality',
  subtitle: 'Find the cause of a data problem using live evidence, then propose a defensible fix.',
  file: 'dump/reece_ai/procedures/snowflake-investigation-and-data-quality.md',
  level: 'L2 read-only',
  objective: 'Start read-only. Confirm object identity, freshness, shape, expected-vs-actual, lineage. Identify which failure class produced the gap before proposing a fix.',
  automation: 'Good first read-only automation candidate. Mutations remain human-approved.',
  accent: COL.discovery,
  phases: [
    { id: 'p-intake',    label: 'INTAKE',    color: COL.intake,    x: 80,   y: -60 },
    { id: 'p-discover',  label: 'DISCOVER',  color: COL.discovery, x: 480,  y: -60 },
    { id: 'p-diagnose',  label: 'DIAGNOSE',  color: COL.execute,   x: 880,  y: -60 },
    { id: 'p-recommend', label: 'RECOMMEND', color: COL.close,     x: 1280, y: -60 },
  ],
  steps: [
    { id: 'capture', label: 'Capture the claim', stepNumber: 1,
      shortDesc: 'Ticket + expected vs actual + object names + date range',
      longDesc: 'Pull out: ticket key, claimed problem, expected vs actual result, object names (fully-qualified), date range, source system, downstream consumer, whether the issue is one-time / recurring / unknown. Vague tickets get vague investigations.',
      outputs: ['A scoped problem statement before any SQL'],
      mandatory: true, x: 40, y: 60,
    },
    { id: 'identity', label: 'Confirm object identity', stepNumber: 2,
      shortDesc: 'Fully qualify DB.SCHEMA.OBJECT; check object type',
      longDesc: 'Is this a table, view, dynamic table, task, stream, procedure, external table, stage, or file format? A "table" might actually be a view backed by a procedure that runs nightly. Check dev/UAT/prod naming carefully — the same name exists in all three.',
      tools: ['scripts/snowflake-query.mjs', 'SHOW OBJECTS', 'INFORMATION_SCHEMA.TABLES'],
      outputs: ['Definitive object type + correct DB.SCHEMA.OBJECT'],
      mandatory: true, x: 440, y: -20,
    },
    { id: 'freshness', label: 'Freshness + volume', stepNumber: 3,
      shortDesc: 'Row count, min/max business date, latest write',
      longDesc: 'Pull row count, min/max of the business date column, latest INSERT_TIME if present. Pull recent write activity from QUERY_HISTORY filtered by the object. If a Snowflake task owns the load, pull TASK_HISTORY.',
      tools: ['INFORMATION_SCHEMA.TABLES.row_count', 'QUERY_HISTORY', 'TASK_HISTORY'],
      outputs: ['Whether the data is stale, missing, or partial'],
      mandatory: true, x: 440, y: 130,
    },
    { id: 'shape', label: 'Check shape', stepNumber: 4,
      shortDesc: 'Columns, nulls, duplicate-key check',
      longDesc: 'List columns + types. Check nulls in business-critical columns. Identify natural key candidates and check for unexpected duplicates. The grain you assume should be the grain the data actually has.',
      tools: ['DESCRIBE TABLE', 'COUNT_IF(col IS NULL)', 'GROUP BY natural_key HAVING count > 1'],
      outputs: ['Quantified null/duplicate report'],
      mandatory: true, x: 440, y: 280,
    },
    { id: 'compare', label: 'Expected vs actual', stepNumber: 5,
      shortDesc: 'Narrow validation query first, then widen',
      longDesc: 'Build a narrow validation query from the ticket\'s actual examples (specific invoice number, specific date, specific customer). Then widen to counts by date, source, status, branch, customer, product. Don\'t assume the business grain — derive it.',
      examples: ['"Why no records for Feb 14?" → start with WHERE date = \'2026-02-14\', then GROUP BY date for that month'],
      outputs: ['Concrete demonstration of where actual diverges from expected'],
      mandatory: true, x: 840, y: -20,
    },
    { id: 'lineage', label: 'Trace lineage', stepNumber: 6,
      shortDesc: 'Dependencies + writers + Talend XML + TMC',
      longDesc: 'Use OBJECT_DEPENDENCIES for views/tasks/procs. Use ACCESS_HISTORY to find what writes to this object. If JDBC or Talend write-patterns appear in QUERY_HISTORY, find the Talend job in the GitHub repo. Check TMC for runtime schedule and context. Static XML is supporting evidence, not authoritative.',
      tools: ['SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES', 'SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY', 'mcp__github__search_code', 'TMC UI'],
      guardrails: ['ACCOUNT_USAGE is not exposed on sandbox accounts', 'Static Talend XML scan misses dynamic table refs'],
      outputs: ['Lineage chain from source to target'],
      mandatory: true, x: 840, y: 130,
    },
    { id: 'failclass', label: 'Identify failure class', stepNumber: 7,
      shortDesc: 'Match the symptom to one of 8 known causes',
      longDesc: 'Match what you observed to: source data changed, source API/SFTP incomplete or delayed, Talend job stopped/failed/wrong-context, TMC runtime context overrode committed defaults, Snowflake object changed shape, permission prevented load/read, transformation logic wrong, or downstream expectation is wrong.',
      examples: ['DE-88: TMC context group silently overrode the committed PROD creds with SBX creds → wrong-context class'],
      outputs: ['Named failure class with supporting evidence'],
      mandatory: true, x: 840, y: 280,
    },
    { id: 'propose', label: 'Propose action', stepNumber: 8,
      shortDesc: 'No-op / backfill / job fix / DDL / grant / clarify',
      longDesc: 'Possible actions: no change needed (explain data semantics), backfill or reload, update ingestion job, update Snowflake transform/view/procedure, create missing object or grant, or ask stakeholder to define the missing business rule. Each option has a different blast radius.',
      outputs: ['One named action with rollback consideration'],
      mandatory: true, x: 1240, y: 60,
    },
    { id: 'jira-comment', label: 'Write Jira comment', stepNumber: 9,
      shortDesc: 'Findings + proposed fix + validation query',
      longDesc: 'Post an evidence-based comment using the template: I checked the live Snowflake objects and found — Object, Current row count/freshness, Expected vs actual, Root cause, Proposed fix, Validation query/result, Remaining question.',
      tools: ['mcp__claude_ai_Atlassian__add_jira_comment'],
      outputs: ['Jira comment'],
      mandatory: true, x: 1240, y: 220,
    },
  ],
  edges: [
    { from: 'capture', to: 'identity', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'identity', to: 'freshness' },
    { from: 'freshness', to: 'shape' },
    { from: 'identity', to: 'compare', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'compare', to: 'lineage' },
    { from: 'lineage', to: 'failclass' },
    { from: 'failclass', to: 'propose', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'propose', to: 'jira-comment' },
  ],
};

// ─── 3. Snowflake objects and permissions ────────────────────────
const OBJECTS: ReeceProcedureSpec = {
  id: 'reece-objects-access',
  title: 'Snowflake Objects and Permissions',
  subtitle: 'Create objects + grant access with the narrowest possible scope.',
  file: 'dump/reece_ai/procedures/snowflake-objects-and-permissions.md',
  level: 'L3 bounded mutation',
  objective: 'Make changes with a clear target, least-privilege scope, and verifiable result. Never grant from a Jira summary alone.',
  automation: 'Bounded grants and dev DDL can be automated after approval gates exist.',
  accent: COL.execute,
  phases: [
    { id: 'p-confirm',  label: 'CONFIRM',  color: COL.intake,    x: 80,   y: -60 },
    { id: 'p-inspect',  label: 'INSPECT',  color: COL.discovery, x: 480,  y: -60 },
    { id: 'p-execute',  label: 'EXECUTE',  color: COL.execute,   x: 880,  y: -60 },
    { id: 'p-validate', label: 'VALIDATE', color: COL.validate,  x: 1280, y: -60 },
  ],
  steps: [
    { id: 'request', label: 'Confirm the request', stepNumber: 1,
      shortDesc: 'Target DB.schema, object type, owner role, reader roles',
      longDesc: 'Pull from the ticket: target database/schema/object, object type, naming convention, source system, owner role, reader roles, layer (landing/staging/curated/analytics/workspace). If anything is missing, ask before drafting DDL.',
      outputs: ['Complete object spec'],
      mandatory: true, x: 40, y: 60,
    },
    { id: 'patterns', label: 'Inspect existing patterns', stepNumber: 2,
      shortDesc: 'Sibling objects, naming, load metadata, grants',
      longDesc: 'Look at sibling schemas/tables in the same layer. Match their naming, data types, load-metadata columns (INSERTED_AT, INSERTED_BY), clustering, tags, masking, grants, comments. Check if the same source already exists in another env.',
      tools: ['SHOW TABLES IN SCHEMA', 'SHOW GRANTS ON', 'DESCRIBE TABLE'],
      outputs: ['Reference pattern + style rules to match'],
      mandatory: true, x: 440, y: -20,
    },
    { id: 'inspect-grants', label: 'Inspect current grants', stepNumber: 3,
      shortDesc: 'Existing user, roles, default role, target-data grants',
      longDesc: 'For permission requests: check if the user exists, what roles they have, default role + warehouse, current grants on the target. If mirroring another user, pull their grants too — verify live, don\'t trust the ticket.',
      tools: ['SHOW USERS LIKE', 'SHOW GRANTS TO USER', 'SHOW GRANTS ON'],
      outputs: ['Delta between current state and requested state'],
      mandatory: true, x: 440, y: 140,
    },
    { id: 'draft', label: 'Draft DDL / grant plan', stepNumber: 4,
      shortDesc: 'Fully-qualified, commented, with rollback',
      longDesc: 'Write DDL with fully-qualified names. Add COMMENT clauses for business-facing objects. Plan grants as: USE WH/DB/SCHEMA + object-level SELECT/INSERT etc. Future grants ONLY when the layer pattern uses them. Include a rollback statement.',
      examples: ['CREATE TABLE LANDING.SYSAID.CURATED_TICKETS (...) COMMENT = \'curated from sysaid_DIGESTION job\'', 'GRANT SELECT ON ALL TABLES IN SCHEMA LANDING.SYSAID TO ROLE TALEND_READER'],
      outputs: ['Reviewable SQL block + rollback'],
      mandatory: true, x: 440, y: 300,
    },
    { id: 'review', label: 'Review with stakeholder', stepNumber: 5,
      shortDesc: 'If columns / grain / retention / source-of-truth unclear',
      longDesc: 'Some questions only humans can answer: which columns are required, what grain (1 row per X), retention, source of truth, who downstream consumes this. Ask before executing if any are ambiguous.',
      outputs: ['Stakeholder sign-off (Jira comment or message)'],
      mandatory: false, x: 840, y: -20,
    },
    { id: 'exec', label: 'Execute', stepNumber: 6,
      shortDesc: 'Set role + warehouse, run DDL, apply grants',
      longDesc: 'USE ROLE <owner-role>. USE WAREHOUSE <appropriate-size-WH>. Run the CREATE. Run the grants separately so a failure in one doesn\'t leave the object orphaned. Capture the QUERY_ID from each statement.',
      tools: ['scripts/snowflake-query.mjs', 'CREATE TABLE/VIEW', 'GRANT'],
      guardrails: ['Confirm account/region before mutation', 'Never grant from summary alone'],
      outputs: ['QUERY_IDs and execution log'],
      mandatory: true, x: 840, y: 140,
    },
    { id: 'validate', label: 'Validate', stepNumber: 7,
      shortDesc: 'SHOW objects, SHOW grants, smoke read',
      longDesc: 'Run SHOW OBJECTS to confirm the object exists. Run SHOW GRANTS ON <object> to confirm grants applied. If safe, do a smoke SELECT using the intended reader role to confirm visibility.',
      tools: ['SHOW OBJECTS', 'SHOW GRANTS ON', 'USE ROLE then SELECT'],
      outputs: ['Validation evidence ready to paste into Jira'],
      mandatory: true, x: 1240, y: 60,
    },
    { id: 'doc', label: 'Document', stepNumber: 8,
      shortDesc: 'Jira comment + Confluence + local catalog',
      longDesc: 'Jira: object name, role, grants, validation. Confluence: only if this is a repeatable process. Local catalog: update the ticket folder + add to LEARNINGS.md if this revealed a new pattern.',
      tools: ['mcp__claude_ai_Atlassian__add_jira_comment'],
      outputs: ['Jira closed-loop comment'],
      mandatory: true, x: 1240, y: 220,
    },
  ],
  edges: [
    { from: 'request', to: 'patterns', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'patterns', to: 'inspect-grants' },
    { from: 'inspect-grants', to: 'draft' },
    { from: 'draft', to: 'review', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'review', to: 'exec' },
    { from: 'exec', to: 'validate', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'validate', to: 'doc' },
  ],
};

// ─── 4. Ingestion job creation ───────────────────────────────────
const INGESTION: ReeceProcedureSpec = {
  id: 'reece-ingestion',
  title: 'Ingestion Job Creation',
  subtitle: 'Build or modify Talend / API / SFTP / Snowflake jobs using Reece patterns.',
  file: 'dump/reece_ai/procedures/ingestion-job-creation.md',
  level: 'L2/L3 gated',
  objective: 'Reuse an existing Reece pattern. Validate source semantics, target semantics, load strategy, runtime guardrails, branch convention, TMC context, and validation before promotion.',
  automation: 'Read-only discovery first; job mutation remains approval-gated.',
  accent: COL.execute,
  phases: [
    { id: 'p-intake',   label: 'INTAKE',   color: COL.intake,    x: 80,   y: -60 },
    { id: 'p-design',   label: 'DESIGN',   color: COL.discovery, x: 480,  y: -60 },
    { id: 'p-build',    label: 'BUILD',    color: COL.execute,   x: 880,  y: -60 },
    { id: 'p-promote',  label: 'PROMOTE',  color: COL.close,     x: 1280, y: -60 },
  ],
  steps: [
    { id: 'spec', label: 'Capture the spec', stepNumber: 1,
      shortDesc: 'Source, target, schedule, load mode, natural key',
      longDesc: 'Source system + endpoint + auth location. Target Snowflake object or outbound destination. Schedule + timezone. Load mode (full / append / merge / file drop). Natural key. Expected row count or validation source. Downstream consumer + sign-off owner.',
      examples: ['projects/reece-talend/intake.md has the canonical form'],
      outputs: ['Complete intake block'],
      mandatory: true, x: 40, y: 60,
    },
    { id: 'reference', label: 'Find a reference job', stepNumber: 2,
      shortDesc: 'Search local catalog + Talend-8 repo',
      longDesc: 'Search dump/reece_ai/jobs/ for similar shape. Search Talend-8 by source system, target schema, component name, destination table. Prefer a working Reece pattern over a generic component design. For Workday → Snowflake, check Ulises\' Prod_Cloud jobs first.',
      tools: ['Grep over dump/reece_ai/jobs/', 'mcp__github__search_code on morsco-reece/Talend-8'],
      outputs: ['Named reference job to fork from'],
      mandatory: true, x: 440, y: -40,
    },
    { id: 'source', label: 'Source semantics', stepNumber: 3,
      shortDesc: 'Pagination, cursor, timezone, retries, deletes',
      longDesc: 'API: how does pagination end (empty page vs short page)? Cursor field? Timezone? What does an empty result look like? Which errors retry? Do deleted/archived source records surface? SFTP: file naming convention + arrival time?',
      outputs: ['Source contract: how to read it correctly'],
      mandatory: true, x: 440, y: 100,
    },
    { id: 'target', label: 'Target semantics', stepNumber: 4,
      shortDesc: 'Layer, DDL, key, history retention',
      longDesc: 'Landing / staging / curated layer. Does the table exist or do you need DDL? Column names + types. Natural key. Load-metadata fields (INSERTED_AT, SOURCE_FILE). History retention. Does downstream expect exact shape matching another table?',
      outputs: ['Target contract: how to write it correctly'],
      mandatory: true, x: 440, y: 240,
    },
    { id: 'load-mode', label: 'Choose load strategy', stepNumber: 5,
      shortDesc: 'MERGE / truncate-reload / append / file output',
      longDesc: 'MERGE = idempotent daily deltas (default). Truncate/reload = only when source is complete and downstream accepts. Append = duplicates impossible or historical-by-design. Staged file = target needs a delivered file (e.g. PriceFx SFTP).',
      examples: ['DE-87 (PriceFX Transaction DS) → staged file output to /filearea/outbound/transaction'],
      outputs: ['One named load strategy'],
      mandatory: true, x: 440, y: 380,
    },
    { id: 'guardrails', label: 'Runtime guardrails', stepNumber: 6,
      shortDesc: 'Fail-fast + retries + logging',
      longDesc: 'Fail fast on missing env label / creds / endpoint. Validate source env when prod vs sandbox matters. Add bounded retries for transient API failures (DE-88 pattern: 4 attempts, growing read timeout, exponential backoff, retry on 408/429/500/502/503/504). Log page counts + output counts.',
      examples: ['DE-88 SysAid retry pattern lives in tJava_4'],
      guardrails: ['TMC context group overrides .item defaults at runtime — override creds in tJava_1 explicitly', 'Do not push .item edits while Studio is open on the same job'],
      outputs: ['Hardened runtime'],
      mandatory: true, x: 840, y: -20,
    },
    { id: 'implement', label: 'Implement', stepNumber: 7,
      shortDesc: 'Edit on main_UAT_Jano; commit with Jira key',
      longDesc: 'Author on Alejandro\'s personal UAT branch (main_UAT_Jano) for Reece Talend work. Don\'t create feature branches unless explicitly asked. Keep edits scoped. Use idempotent SQL. Validate file format: delimiter, encoding, header, null handling, filename, delivery path.',
      tools: ['Edit on dump/talend-8-main/...', 'git on main_UAT_Jano', 'mcp__github__create_or_update_file'],
      guardrails: ['Push to main_UAT_Jano, not feature branches', 'Coordinate with Studio if user is editing same .item'],
      outputs: ['Committed .item changes on main_UAT_Jano'],
      mandatory: true, x: 840, y: 140,
    },
    { id: 'tmc-validate', label: 'Validate in Studio / TMC', stepNumber: 8,
      shortDesc: 'Compile, run, source/target counts, dup/null checks',
      longDesc: 'Pull in Studio, F5 to re-render. Run the job (or trigger from TMC). Capture: compile/run status, source records read, target rows written, duplicate-key check, null-critical-field check, sample business rows. Confirm schedule + context values in TMC match expectation.',
      outputs: ['Validation evidence ready for Jira'],
      mandatory: true, x: 840, y: 280,
    },
    { id: 'promote', label: 'Promote / hand off', stepNumber: 9,
      shortDesc: 'Stakeholder sign-off + TMC schedule + Jira',
      longDesc: 'For business-rule changes: ask the stakeholder to validate the output before declaring done. Confirm the TMC schedule and runtime environment. Post the Jira update with: source, target, job path, branch/commit, runtime env, schedule, load strategy, validation, remaining dependency.',
      tools: ['mcp__claude_ai_Atlassian__add_jira_comment'],
      outputs: ['Job in production + closed Jira ticket'],
      mandatory: true, x: 1240, y: 140,
    },
  ],
  edges: [
    { from: 'spec', to: 'reference', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'reference', to: 'source' },
    { from: 'source', to: 'target' },
    { from: 'target', to: 'load-mode' },
    { from: 'load-mode', to: 'guardrails', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'guardrails', to: 'implement' },
    { from: 'implement', to: 'tmc-validate' },
    { from: 'tmc-validate', to: 'promote', sourceHandle: 'right', targetHandle: 'left' },
  ],
};

// ─── 5. Jira and Confluence workflow ─────────────────────────────
const ATLASSIAN: ReeceProcedureSpec = {
  id: 'reece-jira-confluence',
  title: 'Jira and Confluence Workflow',
  subtitle: 'Jira = operational record. Confluence = durable process record. Local catalog = AI context.',
  file: 'dump/reece_ai/procedures/jira-and-confluence-workflow.md',
  level: 'L2 reporting',
  objective: 'Make Jira reflect the actual current state. Lift repeatable processes into Confluence. Keep local notes that help future AI-assisted tickets.',
  automation: 'Comment + page drafts are safe early automation. Publishing remains gated unless using approved templates.',
  accent: COL.close,
  phases: [
    { id: 'p-jira',       label: 'JIRA',       color: COL.intake,    x: 80,   y: -60 },
    { id: 'p-confluence', label: 'CONFLUENCE', color: COL.discovery, x: 720,  y: -60 },
    { id: 'p-catalog',    label: 'CATALOG',    color: COL.close,     x: 1280, y: -60 },
  ],
  steps: [
    { id: 'read', label: 'Read before acting', stepNumber: 1,
      shortDesc: 'Description + acceptance + epic + comments + attachments',
      longDesc: 'Read the description, acceptance criteria, parent epic, linked issues, all comments in order, and every attachment. Most Jira ambiguity dissolves when you actually read every comment.',
      outputs: ['Mental model of the request'],
      mandatory: true, x: 40, y: 60,
    },
    { id: 'clarify', label: 'Clarify only blockers', stepNumber: 2,
      shortDesc: 'Ask only questions that block scope / DoD / sign-off',
      longDesc: 'Use Jira comments when the question affects scope, definition of done, or stakeholder sign-off. Do NOT ask questions that can be answered by live system inspection — investigate first.',
      examples: ['Bad: "what table holds this?" (you can check)', 'Good: "is the target row-per-invoice or row-per-line?" (business rule)'],
      outputs: ['Resolved blocker OR confirmed proceed'],
      mandatory: false, x: 40, y: 220,
    },
    { id: 'evidence', label: 'Post evidence-based update', stepNumber: 3,
      shortDesc: 'Checked / found / changed / validated / next',
      longDesc: 'Every Jira comment should state: what was checked (live systems), what was found (with object names), what changed (with branch/commit), what was validated (with query/test), and what is still needed. Include fully-qualified Snowflake names + Talend job paths.',
      tools: ['mcp__claude_ai_Atlassian__add_jira_comment'],
      guardrails: ['Never paste credentials/tokens/secrets/sensitive exports'],
      outputs: ['Jira comment a reviewer can act on'],
      mandatory: true, x: 320, y: 60,
    },
    { id: 'closer', label: 'Close only when validated', stepNumber: 4,
      shortDesc: 'Not "code changed" — requester-facing outcome works',
      longDesc: 'A ticket is not done because code was changed. It is done when the requester-facing outcome works, OR the remaining owner is clearly identified and the handoff is recorded.',
      outputs: ['Jira status = Done OR explicit handoff'],
      mandatory: true, x: 320, y: 220,
    },
    { id: 'page-needed', label: 'Confluence page needed?', stepNumber: 5,
      shortDesc: 'Repeatable process / standard / runbook / dictionary',
      longDesc: 'Create or update a Confluence page when: a process will repeat, a Snowflake access/object standard exists, a runbook is needed for support, stakeholders need an artifact outside Jira, or a migration/data dictionary needs a stakeholder-ready summary.',
      outputs: ['Decision: skip / draft / publish'],
      mandatory: false, x: 680, y: 60,
    },
    { id: 'page-write', label: 'Write the page', stepNumber: 6,
      shortDesc: 'Purpose, Scope, Prereqs, Procedure, Validation, Troubleshooting, Owners',
      longDesc: 'Use the standard 7-section structure: Purpose, Scope, Prerequisites, Procedure, Validation, Troubleshooting, Owners, Related Jira tickets. Keep credentials out. Cross-link the Jira ticket that spawned the page.',
      tools: ['mcp__claude_ai_Atlassian__create_confluence_page'],
      outputs: ['Confluence page'],
      mandatory: false, x: 680, y: 240,
    },
    { id: 'cat-ticket', label: 'Update ticket notes', stepNumber: 7,
      shortDesc: 'Manual notes section in dump/reece_ai/tickets/DE-XX/',
      longDesc: 'After every meaningful ticket, write hand-authored notes into the MANUAL section below the AUTO:JIRA block. These survive sync runs and give future AI immediate context for similar tickets.',
      tools: ['Edit on dump/reece_ai/tickets/DE-XX/README.md'],
      outputs: ['Persistent ticket context'],
      mandatory: true, x: 1240, y: 60,
    },
    { id: 'cat-job', label: 'Update job notes', stepNumber: 8,
      shortDesc: 'When a Talend job was changed or validated',
      longDesc: 'Update the job\'s README in dump/reece_ai/jobs/ with what changed, why, validation evidence, gotchas hit. Link to the ticket that drove the change.',
      tools: ['Edit on dump/reece_ai/jobs/<slug>/README.md'],
      outputs: ['Persistent job context'],
      mandatory: false, x: 1240, y: 200,
    },
    { id: 'cat-learning', label: 'Add a learning', stepNumber: 9,
      shortDesc: 'Only when likely to prevent future rework',
      longDesc: 'Add a concise durable lesson to LEARNINGS.md only when it would prevent future rework on a similar ticket. Don\'t dump every observation — quality over quantity.',
      tools: ['Edit on dump/reece_ai/LEARNINGS.md'],
      outputs: ['Optionally: a new learning'],
      mandatory: false, x: 1240, y: 340,
    },
  ],
  edges: [
    { from: 'read', to: 'evidence', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'read', to: 'clarify' },
    { from: 'evidence', to: 'closer' },
    { from: 'closer', to: 'page-needed', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'page-needed', to: 'page-write' },
    { from: 'page-needed', to: 'cat-ticket', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'page-write', to: 'cat-ticket', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'cat-ticket', to: 'cat-job' },
    { from: 'cat-job', to: 'cat-learning' },
  ],
};

// ─── 6. Automation roadmap ───────────────────────────────────────
const AUTOMATION: ReeceProcedureSpec = {
  id: 'reece-automation',
  title: 'Automation Roadmap',
  subtitle: 'Move from human-assisted procedures to Jira-read, AI-executed ticket handling.',
  file: 'dump/reece_ai/procedures/automation-roadmap.md',
  level: 'Roadmap',
  objective: 'Automate the procedure, not the guess. Classify → collect evidence → stop on missing inputs → request approval for mutation → validate → report.',
  automation: 'This page IS the automation plan. It defines the path from L0 to L4 closed-loop ticket handling.',
  accent: COL.discovery,
  phases: [
    { id: 'p-l0', label: 'L0 MANUAL',     color: '#666',        x: 60,   y: -60 },
    { id: 'p-l1', label: 'L1 TRIAGE',     color: COL.intake,    x: 360,  y: -60 },
    { id: 'p-l2', label: 'L2 READ-ONLY',  color: COL.discovery, x: 660,  y: -60 },
    { id: 'p-l3', label: 'L3 BOUNDED',    color: COL.execute,   x: 960,  y: -60 },
    { id: 'p-l4', label: 'L4 CLOSED-LOOP', color: COL.close,    x: 1260, y: -60 },
  ],
  steps: [
    { id: 'l0', label: 'Manual procedure', stepNumber: 0,
      shortDesc: 'Human reads Jira; AI assists; human approves mutations',
      longDesc: 'Current state for most tickets. AI follows these markdown runbooks, drafts Jira updates, human approves anything that touches a system. Required components: working AI agent, vault catalog, mcp__* tool surface.',
      outputs: ['Time-saved on routine triage'],
      mandatory: true, x: 20, y: 60,
    },
    { id: 'l1', label: 'Assisted triage', stepNumber: 1,
      shortDesc: 'Agent classifies, finds related context, produces plan',
      longDesc: 'Agent reads Jira through the catalog sync. Classifies request type. Finds related tickets/jobs/systems/Confluence pages. Produces a plan + missing-inputs list. Human still approves execution. Required: procedure classifier + procedure manifest + catalog index.',
      tools: ['scripts/reece-catalog-sync.mjs', 'procedure-manifest.json'],
      outputs: ['Suggested procedure + missing-inputs list'],
      mandatory: true, x: 320, y: 60,
    },
    { id: 'l2', label: 'Read-only investigation', stepNumber: 2,
      shortDesc: 'Agent runs approved Snowflake + GitHub discovery',
      longDesc: 'Agent runs approved read-only discovery: Snowflake metadata + counts + grants + lineage, Talend GitHub references, TMC schedule. Drafts findings. Human approves mutation. Required: evidence collector + read-only tool permissions.',
      tools: ['scripts/snowflake-query.mjs (read-only)', 'mcp__github__search_code'],
      guardrails: ['Stop after 1-2 auth failures', 'No prod writes during investigation'],
      outputs: ['Draft findings + recommended action'],
      mandatory: true, x: 620, y: 60,
    },
    { id: 'l3', label: 'Bounded execution', stepNumber: 3,
      shortDesc: 'Pre-approved low-risk mutations',
      longDesc: 'Agent can execute pre-approved low-risk changes: dev DDL from reviewed templates, standard grants, validation queries, local catalog updates, Jira/Confluence drafts. Prod data mutations + job promotions stay human-approved. Required: change executor + approval gates + rollback logging.',
      tools: ['scripts/snowflake-query.mjs (write, gated)', 'Edit/Write on Talend XML (gated)'],
      guardrails: ['Explicit target object/branch/role required', 'Rollback plan logged before execution'],
      outputs: ['Pre-approved low-risk changes executed automatically'],
      mandatory: true, x: 920, y: 60,
    },
    { id: 'l4', label: 'Closed-loop automation', stepNumber: 4,
      shortDesc: 'Reads Jira → executes safe procedure → comments back',
      longDesc: 'Agent reads assigned Jira tickets. Classifies and runs known safe procedures end-to-end. Creates branches/commits. Validates with machine-checkable gates. Comments in Jira with evidence. Escalates only unresolved decisions or unsafe mutations. Required: validator + reporter + Jira write loop.',
      tools: ['Full mcp__claude_ai_Atlassian__* surface', 'scripts/reece-catalog-sync.mjs'],
      outputs: ['Tickets handled end-to-end without human in the loop for the common case'],
      mandatory: true, x: 1220, y: 60,
    },
    { id: 'contract', label: 'Ticket automation contract', stepNumber: 5,
      shortDesc: 'Structured record per ticket run',
      longDesc: 'Every automated ticket run produces a JSON record with: ticket key, classification, procedure used, confidence, evidence list, plan, mutations requested + executed, validation results, Jira comment draft, blocked-on items. Enables retroactive audit + measurement.',
      examples: ['See `automation-roadmap.md` for the schema'],
      outputs: ['Auditable per-ticket run log'],
      mandatory: true, x: 620, y: 260,
    },
    { id: 'candidates', label: 'Good first candidates', stepNumber: 6,
      shortDesc: 'Investigations + access mirrors + DDL drafts',
      longDesc: 'Start with: read-only Snowflake inconsistency investigations, access mirroring (when requester + model user are explicit), object existence + DDL draft generation, Jira status summaries from live evidence, Confluence drafts from completed procedures. AVOID: prod data deletes, ambiguous business rules, Talend rewrites while Studio is open, integrations with unknown source semantics.',
      outputs: ['Prioritized list of automation targets'],
      mandatory: true, x: 920, y: 260,
    },
  ],
  edges: [
    { from: 'l0', to: 'l1', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'l1', to: 'l2', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'l2', to: 'l3', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'l3', to: 'l4', sourceHandle: 'right', targetHandle: 'left' },
    { from: 'l2', to: 'contract' },
    { from: 'l3', to: 'candidates' },
  ],
};

export const REECE_PROCEDURE_SPECS: ReeceProcedureSpec[] = [
  INTAKE, DATA_QA, OBJECTS, INGESTION, ATLASSIAN, AUTOMATION,
];

export const REECE_PROCEDURE_SHORT: Record<string, string> = {
  'reece-intake': 'Intake',
  'reece-data-quality': 'Data QA',
  'reece-objects-access': 'Objects',
  'reece-ingestion': 'Ingestion',
  'reece-jira-confluence': 'Atlassian',
  'reece-automation': 'Roadmap',
};
