#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# JANUS IA — SKILLS REGISTRY RECONCILER
#
# Rewrites the auto-managed block of skills/registry.md to match
# disk truth. Replaces the section between:
#   <!-- BEGIN AUTO-RECONCILED -->
#   <!-- END AUTO-RECONCILED -->
#
# Audit 2026-04-28: skills/registry.md was claiming 5+ skills "INSTALLED
# AND WORKING" while ~/.claude/skills/ was empty. Reminder-style
# accuracy doesn't survive Codespace ephemerality. This reconciler
# makes the registry truthful by construction — it can never lie again.
#
# Idempotent. Safe to run on every preflight. Prints a one-line summary
# to stdout for the preflight banner.
# ═══════════════════════════════════════════════════════════════

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
WORKSPACE="${WORKSPACE_ROOT:-$SCRIPT_DIR}"
REGISTRY="$WORKSPACE/skills/registry.md"

[ ! -f "$REGISTRY" ] && exit 0

# ─── Inventory ─────────────────────────────────────────────────
# Source of truth: SKILL.md files. The skill name is the parent dir.
# This catches arbitrary plugin layouts:
#   plugins/<x>/skills/<skill>/SKILL.md
#   external_plugins/<x>/skills/<skill>/SKILL.md
#   ~/.claude/skills/<skill>/SKILL.md
#   /mnt/skills/public/<skill>/SKILL.md  (if present)
list_skills_under() {
  local root="$1"
  [ ! -d "$root" ] && return 0
  find "$root" -name SKILL.md -type f 2>/dev/null \
    | while read -r f; do basename "$(dirname "$f")"; done \
    | sort -u
}

BUILTIN_LIST=$(list_skills_under /mnt/skills)
USER_LIST=$(list_skills_under "$HOME/.claude/skills")
PLUGIN_LIST=$(list_skills_under "$HOME/.claude/plugins/marketplaces")

BUILTIN_N=$(echo -n "$BUILTIN_LIST" | grep -c . || true)
USER_N=$(echo -n "$USER_LIST" | grep -c . || true)
PLUGIN_N=$(echo -n "$PLUGIN_LIST" | grep -c . || true)
TOTAL=$((BUILTIN_N + USER_N + PLUGIN_N))

# ─── Build the auto block ──────────────────────────────────────
TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
TMP=$(mktemp)
{
  echo "<!-- BEGIN AUTO-RECONCILED -->"
  echo "<!-- This block is regenerated by scripts/reconcile-skills.sh on every session start. -->"
  echo "<!-- Do not edit by hand — your changes will be overwritten. Last reconciled: $TS -->"
  echo ""
  echo "## CURRENTLY INSTALLED (auto)"
  echo ""
  echo "Reconciled from disk at session start. Reflects ground truth — what the AI can actually invoke."
  echo ""
  echo "**Counts:** ${BUILTIN_N} built-in · ${USER_N} user-installed · ${PLUGIN_N} plugin · **${TOTAL} total**"
  echo ""
  if [ "$BUILTIN_N" -gt 0 ]; then
    echo "### Built-in (\`/mnt/skills/public/\`)"
    echo "Always available. Survive Codespace recycling."
    echo ""
    echo "$BUILTIN_LIST" | sed 's/^/- /'
    echo ""
  fi
  if [ "$USER_N" -gt 0 ]; then
    echo "### User-installed (\`~/.claude/skills/\`)"
    echo "Wiped when the Codespace recycles. Re-install via \`scripts/install-skills.sh\` if missing."
    echo ""
    echo "$USER_LIST" | sed 's/^/- /'
    echo ""
  else
    echo "### User-installed (\`~/.claude/skills/\`)"
    echo "**Empty.** This is the default after a Codespace rebuild — \`npx skills add\` installs go here and don't survive."
    echo "If you need user-installed skills, add them to \`scripts/install-skills.sh\` so they re-install automatically."
    echo ""
  fi
  if [ "$PLUGIN_N" -gt 0 ]; then
    echo "### Plugin-marketplace (\`~/.claude/plugins/marketplaces/\`)"
    echo "Installed via \`/plugin marketplace add\`. Persistent across Codespace rebuilds."
    echo ""
    echo "$PLUGIN_LIST" | sed 's/^/- /'
    echo ""
  fi
  echo "<!-- END AUTO-RECONCILED -->"
} > "$TMP"

# ─── Splice into the registry ──────────────────────────────────
if grep -q "<!-- BEGIN AUTO-RECONCILED -->" "$REGISTRY"; then
  # Replace existing block in-place
  python3 - <<PY
import re
path = "$REGISTRY"
new_block = open("$TMP").read().rstrip() + "\n"
src = open(path).read()
out = re.sub(
    r'<!-- BEGIN AUTO-RECONCILED -->.*?<!-- END AUTO-RECONCILED -->\n?',
    new_block,
    src,
    flags=re.DOTALL,
    count=1,
)
open(path, 'w').write(out)
PY
else
  # Insert after the top header (line containing "# SKILLS REGISTRY")
  python3 - <<PY
path = "$REGISTRY"
new_block = open("$TMP").read().rstrip() + "\n"
src = open(path).read()
lines = src.split("\n")
# Find the first blank line after "# SKILLS REGISTRY" header
insert_at = 0
for i, line in enumerate(lines):
    if line.startswith("# SKILLS REGISTRY"):
        # find next blank
        for j in range(i+1, len(lines)):
            if not lines[j].strip():
                insert_at = j + 1
                break
        break
new_lines = lines[:insert_at] + ["", new_block.rstrip(), ""] + lines[insert_at:]
open(path, 'w').write("\n".join(new_lines))
PY
fi

rm -f "$TMP"

echo "  Skills (reconciled): ${BUILTIN_N} built-in · ${USER_N} user-installed · ${PLUGIN_N} plugin"
